// SPDX-FileCopyrightText: 2013 Mark Hessling <mark@rexx.org>
// SPDX-License-Identifier: GPL-2.0
// SPDX-FileContributor: 2022 Ben Ravago

#include "getch.h"

struct key_values {
  uchar *mnemonic;
  int key_value;
  int shift;
};
typedef struct key_values KEYS;

KEYS key_table[] = {
  { (uchar *) "A", (int) 'a', 0 },
  { (uchar *) "B", (int) 'b', 0 },
  { (uchar *) "C", (int) 'c', 0 },
  { (uchar *) "D", (int) 'd', 0 },
  { (uchar *) "E", (int) 'e', 0 },
  { (uchar *) "F", (int) 'f', 0 },
  { (uchar *) "G", (int) 'g', 0 },
  { (uchar *) "H", (int) 'h', 0 },
  { (uchar *) "I", (int) 'i', 0 },
  { (uchar *) "J", (int) 'j', 0 },
  { (uchar *) "K", (int) 'k', 0 },
  { (uchar *) "L", (int) 'l', 0 },
  { (uchar *) "M", (int) 'm', 0 },
  { (uchar *) "N", (int) 'n', 0 },
  { (uchar *) "O", (int) 'o', 0 },
  { (uchar *) "P", (int) 'p', 0 },
  { (uchar *) "Q", (int) 'q', 0 },
  { (uchar *) "R", (int) 'r', 0 },
  { (uchar *) "S", (int) 's', 0 },
  { (uchar *) "T", (int) 't', 0 },
  { (uchar *) "U", (int) 'u', 0 },
  { (uchar *) "V", (int) 'v', 0 },
  { (uchar *) "W", (int) 'w', 0 },
  { (uchar *) "X", (int) 'x', 0 },
  { (uchar *) "Y", (int) 'y', 0 },
  { (uchar *) "Z", (int) 'z', 0 },
  { (uchar *) "S-A", (int) 'A', SHIFT_SHIFT },
  { (uchar *) "S-B", (int) 'B', SHIFT_SHIFT },
  { (uchar *) "S-C", (int) 'C', SHIFT_SHIFT },
  { (uchar *) "S-D", (int) 'D', SHIFT_SHIFT },
  { (uchar *) "S-E", (int) 'E', SHIFT_SHIFT },
  { (uchar *) "S-F", (int) 'F', SHIFT_SHIFT },
  { (uchar *) "S-G", (int) 'G', SHIFT_SHIFT },
  { (uchar *) "S-H", (int) 'H', SHIFT_SHIFT },
  { (uchar *) "S-I", (int) 'I', SHIFT_SHIFT },
  { (uchar *) "S-J", (int) 'J', SHIFT_SHIFT },
  { (uchar *) "S-K", (int) 'K', SHIFT_SHIFT },
  { (uchar *) "S-L", (int) 'L', SHIFT_SHIFT },
  { (uchar *) "S-M", (int) 'M', SHIFT_SHIFT },
  { (uchar *) "S-N", (int) 'N', SHIFT_SHIFT },
  { (uchar *) "S-O", (int) 'O', SHIFT_SHIFT },
  { (uchar *) "S-P", (int) 'P', SHIFT_SHIFT },
  { (uchar *) "S-Q", (int) 'Q', SHIFT_SHIFT },
  { (uchar *) "S-R", (int) 'R', SHIFT_SHIFT },
  { (uchar *) "S-S", (int) 'S', SHIFT_SHIFT },
  { (uchar *) "S-T", (int) 'T', SHIFT_SHIFT },
  { (uchar *) "S-U", (int) 'U', SHIFT_SHIFT },
  { (uchar *) "S-V", (int) 'V', SHIFT_SHIFT },
  { (uchar *) "S-W", (int) 'W', SHIFT_SHIFT },
  { (uchar *) "S-X", (int) 'X', SHIFT_SHIFT },
  { (uchar *) "S-Y", (int) 'Y', SHIFT_SHIFT },
  { (uchar *) "S-Z", (int) 'Z', SHIFT_SHIFT },
  { (uchar *) "0", (int) '0', 0 },
  { (uchar *) "1", (int) '1', 0 },
  { (uchar *) "2", (int) '2', 0 },
  { (uchar *) "3", (int) '3', 0 },
  { (uchar *) "4", (int) '4', 0 },
  { (uchar *) "5", (int) '5', 0 },
  { (uchar *) "6", (int) '6', 0 },
  { (uchar *) "7", (int) '7', 0 },
  { (uchar *) "8", (int) '8', 0 },
  { (uchar *) "9", (int) '9', 0 },
  { (uchar *) "`", (int) '`', 0 },
  { (uchar *) "-", (int) '-', 0 },
  { (uchar *) "=", (int) '=', 0 },
  { (uchar *) "[", (int) '[', 0 },
  { (uchar *) "]", (int) ']', 0 },
  { (uchar *) "\\", (int) '\\', 0 },
  { (uchar *) ";", (int) ';', 0 },
  { (uchar *) "'", (int) '\'', 0 },
  { (uchar *) ",", (int) ',', 0 },
  { (uchar *) ".", (int) '.', 0 },
  { (uchar *) "/", (int) '/', 0 },
  { (uchar *) ")", (int) ')', 0 },
  { (uchar *) "!", (int) '!', 0 },
  { (uchar *) "@", (int) '@', 0 },
  { (uchar *) "#", (int) '#', 0 },
  { (uchar *) "$", (int) '$', 0 },
  { (uchar *) "%", (int) '%', 0 },
  { (uchar *) "^", (int) '^', 0 },
  { (uchar *) "&", (int) '&', 0 },
  { (uchar *) "*", (int) '*', 0 },
  { (uchar *) "(", (int) '(', 0 },
  { (uchar *) "~", (int) '~', 0 },
  { (uchar *) "_", (int) '_', 0 },
  { (uchar *) "+", (int) '+', 0 },
  { (uchar *) "{", (int) '{', 0 },
  { (uchar *) "}", (int) '}', 0 },
  { (uchar *) "|", (int) '|', 0 },
  { (uchar *) ":", (int) ':', 0 },
  { (uchar *) "\"", (int) '\"', 0 },
  { (uchar *) "<", (int) '<', 0 },
  { (uchar *) ">", (int) '>', 0 },
  { (uchar *) "?", (int) '?', 0 },
  { (uchar *) "SPACE", (int) ' ', 0 },
  { (uchar *) "ESC", KEY_ESC, 0 },
  { (uchar *) "F0", KEY_F0, 0 },
  { (uchar *) "F1", KEY_F1, 0 },
  { (uchar *) "F2", KEY_F2, 0 },
  { (uchar *) "F3", KEY_F3, 0 },
  { (uchar *) "F4", KEY_F4, 0 },
  { (uchar *) "F5", KEY_F5, 0 },
  { (uchar *) "F6", KEY_F6, 0 },
  { (uchar *) "F7", KEY_F7, 0 },
  { (uchar *) "F8", KEY_F8, 0 },
  { (uchar *) "F9", KEY_F9, 0 },
  { (uchar *) "F10", KEY_F10, 0 },
  { (uchar *) "F11", KEY_F11, 0 },
  { (uchar *) "F12", KEY_F12, 0 },
  { (uchar *) "S-F1", KEY_S_F1, SHIFT_SHIFT },
  { (uchar *) "S-F2", KEY_S_F2, SHIFT_SHIFT },
  { (uchar *) "S-F3", KEY_S_F3, SHIFT_SHIFT },
  { (uchar *) "S-F4", KEY_S_F4, SHIFT_SHIFT },
  { (uchar *) "S-F5", KEY_S_F5, SHIFT_SHIFT },
  { (uchar *) "S-F6", KEY_S_F6, SHIFT_SHIFT },
  { (uchar *) "S-F7", KEY_S_F7, SHIFT_SHIFT },
  { (uchar *) "S-F8", KEY_S_F8, SHIFT_SHIFT },
  { (uchar *) "S-F9", KEY_S_F9, SHIFT_SHIFT },
  { (uchar *) "S-F10", KEY_S_F10, SHIFT_SHIFT },
  { (uchar *) "S-F11", KEY_S_F11, SHIFT_SHIFT },
  { (uchar *) "S-F12", KEY_S_F12, SHIFT_SHIFT },
  { (uchar *) "C-F1", KEY_C_F1, SHIFT_CTRL },
  { (uchar *) "C-F2", KEY_C_F2, SHIFT_CTRL },
  { (uchar *) "C-F3", KEY_C_F3, SHIFT_CTRL },
  { (uchar *) "C-F4", KEY_C_F4, SHIFT_CTRL },
  { (uchar *) "C-F5", KEY_C_F5, SHIFT_CTRL },
  { (uchar *) "C-F6", KEY_C_F6, SHIFT_CTRL },
  { (uchar *) "C-F7", KEY_C_F7, SHIFT_CTRL },
  { (uchar *) "C-F8", KEY_C_F8, SHIFT_CTRL },
  { (uchar *) "C-F9", KEY_C_F9, SHIFT_CTRL },
  { (uchar *) "C-F10", KEY_C_F10, SHIFT_CTRL },
  { (uchar *) "C-F11", KEY_C_F11, SHIFT_CTRL },
  { (uchar *) "C-F12", KEY_C_F12, SHIFT_CTRL },
  { (uchar *) "A-F1", KEY_A_F1, SHIFT_ALT },
  { (uchar *) "A-F2", KEY_A_F2, SHIFT_ALT },
  { (uchar *) "A-F3", KEY_A_F3, SHIFT_ALT },
  { (uchar *) "A-F4", KEY_A_F4, SHIFT_ALT },
  { (uchar *) "A-F5", KEY_A_F5, SHIFT_ALT },
  { (uchar *) "A-F6", KEY_A_F6, SHIFT_ALT },
  { (uchar *) "A-F7", KEY_A_F7, SHIFT_ALT },
  { (uchar *) "A-F8", KEY_A_F8, SHIFT_ALT },
  { (uchar *) "A-F9", KEY_A_F9, SHIFT_ALT },
  { (uchar *) "A-F10", KEY_A_F10, SHIFT_ALT },
  { (uchar *) "A-F11", KEY_A_F11, SHIFT_ALT },
  { (uchar *) "A-F12", KEY_A_F12, SHIFT_ALT },
  { (uchar *) "F13", KEY_F13, 0 },
  { (uchar *) "F14", KEY_F14, 0 },
  { (uchar *) "F15", KEY_F15, 0 },
  { (uchar *) "F16", KEY_F16, 0 },
  { (uchar *) "F17", KEY_F17, 0 },
  { (uchar *) "F18", KEY_F18, 0 },
  { (uchar *) "F19", KEY_F19, 0 },
  { (uchar *) "F20", KEY_F20, 0 },
  { (uchar *) "S-F13", KEY_S_F13, SHIFT_SHIFT },
  { (uchar *) "S-F14", KEY_S_F14, SHIFT_SHIFT },
  { (uchar *) "S-F15", KEY_S_F15, SHIFT_SHIFT },
  { (uchar *) "S-F16", KEY_S_F16, SHIFT_SHIFT },
  { (uchar *) "S-F17", KEY_S_F17, SHIFT_SHIFT },
  { (uchar *) "S-F18", KEY_S_F18, SHIFT_SHIFT },
  { (uchar *) "S-F19", KEY_S_F19, SHIFT_SHIFT },
  { (uchar *) "NUM0", KEY_Pad0, 0 },
  { (uchar *) "NUM1", KEY_C1, 0 },
  { (uchar *) "NUM2", KEY_C2, 0 },
  { (uchar *) "NUM3", KEY_C3, 0 },
  { (uchar *) "NUM4", KEY_B1, 0 },
  { (uchar *) "CENTER", KEY_B2, 0 },
  { (uchar *) "NUM6", KEY_B3, 0 },
  { (uchar *) "NUM7", KEY_A1, 0 },
  { (uchar *) "NUM8", KEY_A2, 0 },
  { (uchar *) "NUM9", KEY_A3, 0 },

  { (uchar *) "BKSP", KEY_BKSP, 0 },
  { (uchar *) "ENTER", KEY_RETURN, 0 },
  { (uchar *) "ENTER", KEY_ENTER, 0 },

  { (uchar *) "CURD", KEY_DOWN, 0 },
  { (uchar *) "CURU", KEY_UP, 0 },
  { (uchar *) "CURL", KEY_LEFT, 0 },
  { (uchar *) "CURR", KEY_RIGHT, 0 },
  { (uchar *) "BACKSPACE", KEY_BACKSPACE, 0 },
  { (uchar *) "HOME", KEY_HOME, 0 },
  { (uchar *) "PF1", KEY_PF1, 0 },
  { (uchar *) "PF2", KEY_PF2, 0 },
  { (uchar *) "PF3", KEY_PF3, 0 },
  { (uchar *) "PF4", KEY_PF4, 0 },
  { (uchar *) "NUMENTER", KEY_NUMENTER, 0 },
  { (uchar *) "MINUS", KEY_PadMinus, 0 },
  { (uchar *) "NUMSTOP", KEY_PadPeriod, 0 },
  { (uchar *) "COMMA", KEY_PadComma, 0 },
  { (uchar *) "STAR", KEY_PadStar, 0 },
  { (uchar *) "PLUS", KEY_PadPlus, 0 },
  { (uchar *) "SLASH", KEY_PadSlash, 0 },
  { (uchar *) "S-TAB", KEY_BTAB, SHIFT_SHIFT },
  { (uchar *) "FIND", KEY_Find, 0 },
  { (uchar *) "INS", KEY_InsertHere, 0 },
  { (uchar *) "REMOVE", KEY_Remove, 0 },
  { (uchar *) "DEL", KEY_DELETE, 0 },
  { (uchar *) "SELECT", KEY_Select, 0 },
  { (uchar *) "PGUP", KEY_PrevScreen, 0 },
  { (uchar *) "PGDN", KEY_NextScreen, 0 },
  { (uchar *) "TAB", KEY_C_i, 0 },
  { (uchar *) "RETURN", KEY_RETURN, 0 },
  { (uchar *) "CSI", CSI, 0 },
  { (uchar *) "BREAK", KEY_BREAK, 0 },
  { (uchar *) "DL", KEY_DL, 0 },
  { (uchar *) "IL", KEY_IL, 0 },
  { (uchar *) "DC", KEY_DC, 0 },
  { (uchar *) "INS", KEY_IC, 0 },
  { (uchar *) "EIC", KEY_EIC, 0 },
  { (uchar *) "CLEAR", KEY_CLEAR, 0 },
  { (uchar *) "EOS", KEY_EOS, 0 },
  { (uchar *) "EOL", KEY_EOL, 0 },
  { (uchar *) "SF", KEY_SF, 0 },
  { (uchar *) "SR", KEY_SR, 0 },
  { (uchar *) "PGDN", KEY_NPAGE, 0 },
  { (uchar *) "PGUP", KEY_PPAGE, 0 },
  { (uchar *) "S-TAB", KEY_STAB, SHIFT_SHIFT },
  { (uchar *) "C-TAB", KEY_CTAB, SHIFT_CTRL },
  { (uchar *) "CATAB", KEY_CATAB, 0 },
  { (uchar *) "ENTER", KEY_ENTER, 0 },
  { (uchar *) "S-RESET", KEY_SRESET, SHIFT_SHIFT },
  { (uchar *) "RESET", KEY_RESET, 0 },
  { (uchar *) "PRINT", KEY_PRINT, 0 },
  { (uchar *) "LL", KEY_LL, 0 },
  { (uchar *) "A1", KEY_A1, 0 },
  { (uchar *) "A3", KEY_A3, 0 },
  { (uchar *) "B2", KEY_B2, 0 },
  { (uchar *) "C1", KEY_C1, 0 },
  { (uchar *) "C3", KEY_C3, 0 },
  { (uchar *) "S-TAB", KEY_BTAB, SHIFT_SHIFT },
  { (uchar *) "BEG", KEY_BEG, 0 },
  { (uchar *) "CANCEL", KEY_CANCEL, 0 },
  { (uchar *) "CLOSE", KEY_CLOSE, 0 },
  { (uchar *) "COMMAND", KEY_COMMAND, 0 },
  { (uchar *) "COPY", KEY_COPY, 0 },
  { (uchar *) "CREATE", KEY_CREATE, 0 },
  { (uchar *) "END", KEY_END, 0 },
  { (uchar *) "EXIT", KEY_EXIT, 0 },
  { (uchar *) "FIND", KEY_FIND, 0 },
  { (uchar *) "HELP", KEY_HELP, 0 },
  { (uchar *) "MARK", KEY_MARK, 0 },
  { (uchar *) "MESSAGE", KEY_MESSAGE, 0 },
  { (uchar *) "MOVE", KEY_MOVE, 0 },
  { (uchar *) "NEXT", KEY_NEXT, 0 },
  { (uchar *) "OPEN", KEY_OPEN, 0 },
  { (uchar *) "OPTIONS", KEY_OPTIONS, 0 },
  { (uchar *) "PREVIOUS", KEY_PREVIOUS, 0 },
  { (uchar *) "REDO", KEY_REDO, 0 },
  { (uchar *) "REFERENCE", KEY_REFERENCE, 0 },
  { (uchar *) "REFRESH", KEY_REFRESH, 0 },
  { (uchar *) "REPLACE", KEY_REPLACE, 0 },
  { (uchar *) "RESTART", KEY_RESTART, 0 },
  { (uchar *) "RESUME", KEY_RESUME, 0 },
  { (uchar *) "SAVE", KEY_SAVE, 0 },
  { (uchar *) "S-BEG", KEY_SBEG, SHIFT_SHIFT },
  { (uchar *) "S-CANCEL", KEY_SCANCEL, SHIFT_SHIFT },
  { (uchar *) "S-COMMAND", KEY_SCOMMAND, SHIFT_SHIFT },
  { (uchar *) "S-COPY", KEY_SCOPY, SHIFT_SHIFT },
  { (uchar *) "S-CREATE", KEY_SCREATE, SHIFT_SHIFT },
  { (uchar *) "S-DC", KEY_SDC, SHIFT_SHIFT },
  { (uchar *) "S-DL", KEY_SDL, SHIFT_SHIFT },
  { (uchar *) "SELECT", KEY_SELECT, 0 },
  { (uchar *) "S-END", KEY_SEND, SHIFT_SHIFT },
  { (uchar *) "S-EOL", KEY_SEOL, SHIFT_SHIFT },
  { (uchar *) "S-EXIT", KEY_SEXIT, SHIFT_SHIFT },
  { (uchar *) "S-FIND", KEY_SFIND, SHIFT_SHIFT },
  { (uchar *) "S-HELP", KEY_SHELP, SHIFT_SHIFT },
  { (uchar *) "S-HOME", KEY_SHOME, SHIFT_SHIFT },
  { (uchar *) "S-INS", KEY_SIC, SHIFT_SHIFT },
  { (uchar *) "S-CURL", KEY_SLEFT, SHIFT_SHIFT },
  { (uchar *) "S-MESSAGE", KEY_SMESSAGE, SHIFT_SHIFT },
  { (uchar *) "S-MOVE", KEY_SMOVE, SHIFT_SHIFT },
  { (uchar *) "S-NEXT", KEY_SNEXT, SHIFT_SHIFT },
  { (uchar *) "S-OPTIONS", KEY_SOPTIONS, SHIFT_SHIFT },
  { (uchar *) "S-PREVIOUS", KEY_SPREVIOUS, SHIFT_SHIFT },
  { (uchar *) "S-PRINT", KEY_SPRINT, SHIFT_SHIFT },
  { (uchar *) "S-REDO", KEY_SREDO, SHIFT_SHIFT },
  { (uchar *) "S-REPLACE", KEY_SREPLACE, SHIFT_SHIFT },
  { (uchar *) "S-CURR", KEY_SRIGHT, SHIFT_SHIFT },
  { (uchar *) "S-RSUME", KEY_SRSUME, SHIFT_SHIFT },
  { (uchar *) "S-SAVE", KEY_SSAVE, SHIFT_SHIFT },
  { (uchar *) "S-SUSPEND", KEY_SSUSPEND, SHIFT_SHIFT },
  { (uchar *) "S-UNDO", KEY_SUNDO, SHIFT_SHIFT },
  { (uchar *) "SUSPEND", KEY_SUSPEND, 0 },
  { (uchar *) "UNDO", KEY_UNDO, 0 },
  { (uchar *) "C-CURL", CTL_LEFT, SHIFT_CTRL },
  { (uchar *) "C-CURR", CTL_RIGHT, SHIFT_CTRL },
  { (uchar *) "C-CURU", CTL_UP, SHIFT_CTRL },
  { (uchar *) "C-CURD", CTL_DOWN, SHIFT_CTRL },
  { (uchar *) "C-HOME", CTL_HOME, SHIFT_CTRL },
  { (uchar *) "C-END", CTL_END, SHIFT_CTRL },
  { (uchar *) "C-PGUP", CTL_PGUP, SHIFT_CTRL },
  { (uchar *) "C-PGDN", CTL_PGDN, SHIFT_CTRL },
  { (uchar *) "C-A", (int) KEY_C_a, SHIFT_CTRL },
  { (uchar *) "C-B", (int) KEY_C_b, SHIFT_CTRL },
  { (uchar *) "C-C", (int) KEY_C_c, SHIFT_CTRL },
  { (uchar *) "C-D", (int) KEY_C_d, SHIFT_CTRL },
  { (uchar *) "C-E", (int) KEY_C_e, SHIFT_CTRL },
  { (uchar *) "C-F", (int) KEY_C_f, SHIFT_CTRL },
  { (uchar *) "C-G", (int) KEY_C_g, SHIFT_CTRL },
  { (uchar *) "C-H", (int) KEY_C_h, SHIFT_CTRL },
  { (uchar *) "C-I", (int) KEY_C_i, SHIFT_CTRL },
  { (uchar *) "C-J", (int) KEY_C_j, SHIFT_CTRL },
  { (uchar *) "C-K", (int) KEY_C_k, SHIFT_CTRL },
  { (uchar *) "C-L", (int) KEY_C_l, SHIFT_CTRL },
  { (uchar *) "C-M", (int) KEY_C_m, SHIFT_CTRL },
  { (uchar *) "C-N", (int) KEY_C_n, SHIFT_CTRL },
  { (uchar *) "C-O", (int) KEY_C_o, SHIFT_CTRL },
  { (uchar *) "C-P", (int) KEY_C_p, SHIFT_CTRL },
  { (uchar *) "C-Q", (int) KEY_C_q, SHIFT_CTRL },
  { (uchar *) "C-R", (int) KEY_C_r, SHIFT_CTRL },
  { (uchar *) "C-S", (int) KEY_C_s, SHIFT_CTRL },
  { (uchar *) "C-T", (int) KEY_C_t, SHIFT_CTRL },
  { (uchar *) "C-U", (int) KEY_C_u, SHIFT_CTRL },
  { (uchar *) "C-V", (int) KEY_C_v, SHIFT_CTRL },
  { (uchar *) "C-W", (int) KEY_C_w, SHIFT_CTRL },
  { (uchar *) "C-X", (int) KEY_C_x, SHIFT_CTRL },
  { (uchar *) "C-Y", (int) KEY_C_y, SHIFT_CTRL },
  { (uchar *) "C-Z", (int) KEY_C_z, SHIFT_CTRL },
  { (uchar *) NULL, 0, 0 },
};
