/*
 * THE - The Hessling Editor. A text editor similar to VM/CMS xedit.
 * Copyright (C) 1991-2001 Mark Hessling
 *
 * This program is free software; you can redistribute it and/or
 * modify it under the terms of the GNU General Public License as
 * published by the Free Software Foundation; either version 2 of
 * the License, or any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU
 * General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program; if not, write to:
 *
 *    The Free Software Foundation, Inc.
 *    675 Mass Ave,
 *    Cambridge, MA 02139 USA.
 *
 *
 * If you make modifications to this software that you feel increases
 * it usefulness for the rest of the community, please email the
 * changes, enhancements, bug fixes as well as any and all ideas to me.
 * This software is going to be maintained and enhanced as deemed
 * necessary by the community.
 *
 * Mark Hessling,  M.Hessling@qut.edu.au  http://www.lightlink.com/hessling/
 */

/*
$Id: thedefs.h,v 1.20 2013/07/10 02:07:44 mark Exp $
*/

/*---------------------------------------------------------------------*/
/* Include config.h generated by configure.                            */
/*---------------------------------------------------------------------*/
#include "config.h"

/*---------------------------------------------------------------------*/
/* The following values can be changed to suit your needs.             */
/*---------------------------------------------------------------------*/
#define MAX_FILE_NAME             1000  /* maximum length of fully qualified file */
#define MAX_LENGTH_OF_LINE        1000  /* default maximum length of a line */
#define MAX_COMMANDS                10  /* default maximum number of commands allowed on command line */
#define MAX_RECV                    20  /* number of lines that can be recovered */
#define MAX_SAVED_COMMANDS          20  /* number of commands that can be retrieved */
#define MAX_NUMTABS                 32  /* number of tab stops that can be defined */
#define MAXIMUM_POPUP_KEYS          20  /* maximum number of keys in popup menu */
#define MAXIMUM_DIALOG_LINES       100  /* maximum number of lines in a dailog */

/*---------------------------------------------------------------------*/
/* The following values should not be changed unless you know what you */
/* are doing !                                                         */
/*---------------------------------------------------------------------*/
typedef unsigned short ROWTYPE;
typedef unsigned short COLTYPE;
typedef unsigned char CHARTYPE;
typedef long LENGTHTYPE;        /* was unsigned short *//* MUST be signed!!! */
typedef long LINETYPE;
typedef unsigned char SELECTTYPE;

/*---------------------------------------------------------------------*/
/* A default char type to avoid compiler warnings.                     */
/*---------------------------------------------------------------------*/
typedef char DEFCHAR;
